create table FsquareShopping_ShoppingCoupon (
	couponId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	code_ VARCHAR(75) null,
	name VARCHAR(75) null,
	description VARCHAR(75) null,
	startDate DATE null,
	endDate DATE null,
	active_ BOOLEAN,
	limitCategories VARCHAR(75) null,
	limitSkus VARCHAR(75) null,
	minOrder DOUBLE,
	discount DOUBLE,
	discountType VARCHAR(75) null,
	maxUses LONG
);

create table FsquareShopping_ShoppingOrder (
	shoppingOrderId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status VARCHAR(75) null,
	number_ VARCHAR(75) null,
	tax DOUBLE,
	shipping DOUBLE,
	totalPrice DOUBLE,
	altShipping VARCHAR(75) null,
	requiresShipping BOOLEAN,
	insure BOOLEAN,
	insurance DOUBLE,
	couponCodes VARCHAR(75) null,
	couponDiscount DOUBLE,
	paymentStatus VARCHAR(75) null,
	billingFirstName VARCHAR(75) null,
	billingLastName VARCHAR(75) null,
	billingEmailAddress VARCHAR(75) null,
	billingCompany VARCHAR(75) null,
	billingStreet VARCHAR(75) null,
	billingCity VARCHAR(75) null,
	billingState VARCHAR(75) null,
	billingZip VARCHAR(75) null,
	billingCountry VARCHAR(75) null,
	billingPhone VARCHAR(75) null,
	shipToBilling BOOLEAN,
	shippingFirstName VARCHAR(75) null,
	shippingLastName VARCHAR(75) null,
	shippingEmailAddress VARCHAR(75) null,
	shippingCompany VARCHAR(75) null,
	shippingStreet VARCHAR(75) null,
	shippingStreet2 VARCHAR(75) null,
	shippingCity VARCHAR(75) null,
	shippingState VARCHAR(75) null,
	shippingPostCode VARCHAR(75) null,
	shippingCountry VARCHAR(75) null,
	shippingPhone VARCHAR(75) null,
	ccName VARCHAR(75) null,
	ccType VARCHAR(75) null,
	ccNumber VARCHAR(75) null,
	ccExpMonth INTEGER,
	ccExpYear INTEGER,
	ccVerNumber VARCHAR(75) null,
	comments VARCHAR(75) null,
	ppTxnId VARCHAR(75) null,
	ppPaymentStatus VARCHAR(75) null,
	ppPaymentGross DOUBLE,
	ppReceiverEmail VARCHAR(75) null,
	ppPayerEmail VARCHAR(75) null,
	sendOrderEmail BOOLEAN,
	sendShippingEmail BOOLEAN,
	shippingMethodId LONG,
	international BOOLEAN
);

create table FsquareShopping_ShoppingOrderItem (
	shoppingOrderItemId LONG not null primary key,
	shoppingOrderId LONG,
	articleId VARCHAR(75) null,
	sku VARCHAR(75) null,
	name VARCHAR(75) null,
	description VARCHAR(75) null,
	properties VARCHAR(75) null,
	price DOUBLE,
	quantity INTEGER,
	shippedDate DATE null
);

create table FsquareShopping_ShoppingShippingMethod (
	shippingMethodId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	price DOUBLE,
	name VARCHAR(75) null,
	description VARCHAR(75) null,
	freeQuantity LONG,
	freeTotal DOUBLE,
	weight DOUBLE,
	defaultShipping BOOLEAN,
	international BOOLEAN,
	shippingType VARCHAR(75) null
);

create table FsquareShopping_ShoppingStore (
	groupId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	cartPageUuid VARCHAR(75) null,
	checkoutPageUuid VARCHAR(75) null,
	onAddToCart VARCHAR(75) null,
	currency_ VARCHAR(75) null,
	country VARCHAR(75) null,
	integrateWithStripe BOOLEAN,
	stripeTestSecretKey VARCHAR(75) null,
	stripeTestPublishableKey VARCHAR(75) null,
	stripeTesting BOOLEAN,
	stripeLiveSecretKey VARCHAR(75) null,
	stripeLivePublishableKey VARCHAR(75) null,
	stripeApiVersion VARCHAR(75) null
);