package com.fsquare.shopping.model.impl;

import com.fsquare.shopping.model.ShoppingStorageLocation;
import com.fsquare.shopping.model.ShoppingStorageLocationModel;
import com.fsquare.shopping.model.ShoppingStorageLocationSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ShoppingStorageLocation service. Represents a row in the &quot;FsquareShopping_ShoppingStorageLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fsquare.shopping.model.ShoppingStorageLocationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ShoppingStorageLocationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ShoppingStorageLocationImpl
 * @see com.fsquare.shopping.model.ShoppingStorageLocation
 * @see com.fsquare.shopping.model.ShoppingStorageLocationModel
 * @generated
 */
@JSON(strict = true)
public class ShoppingStorageLocationModelImpl extends BaseModelImpl<ShoppingStorageLocation>
    implements ShoppingStorageLocationModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a shopping storage location model instance should use the {@link com.fsquare.shopping.model.ShoppingStorageLocation} interface instead.
     */
    public static final String TABLE_NAME = "FsquareShopping_ShoppingStorageLocation";
    public static final Object[][] TABLE_COLUMNS = {
            { "storageLocationId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "name", Types.VARCHAR },
            { "description", Types.VARCHAR },
            { "location", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table FsquareShopping_ShoppingStorageLocation (storageLocationId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,description VARCHAR(75) null,location VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table FsquareShopping_ShoppingStorageLocation";
    public static final String ORDER_BY_JPQL = " ORDER BY shoppingStorageLocation.storageLocationId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY FsquareShopping_ShoppingStorageLocation.storageLocationId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.fsquare.shopping.model.ShoppingStorageLocation"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.fsquare.shopping.model.ShoppingStorageLocation"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.fsquare.shopping.model.ShoppingStorageLocation"),
            true);
    public static long GROUPID_COLUMN_BITMASK = 1L;
    public static long STORAGELOCATIONID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.fsquare.shopping.model.ShoppingStorageLocation"));
    private static ClassLoader _classLoader = ShoppingStorageLocation.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            ShoppingStorageLocation.class
        };
    private long _storageLocationId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _companyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private String _name;
    private String _description;
    private String _location;
    private long _columnBitmask;
    private ShoppingStorageLocation _escapedModel;

    public ShoppingStorageLocationModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static ShoppingStorageLocation toModel(
        ShoppingStorageLocationSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        ShoppingStorageLocation model = new ShoppingStorageLocationImpl();

        model.setStorageLocationId(soapModel.getStorageLocationId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setName(soapModel.getName());
        model.setDescription(soapModel.getDescription());
        model.setLocation(soapModel.getLocation());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<ShoppingStorageLocation> toModels(
        ShoppingStorageLocationSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<ShoppingStorageLocation> models = new ArrayList<ShoppingStorageLocation>(soapModels.length);

        for (ShoppingStorageLocationSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _storageLocationId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setStorageLocationId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _storageLocationId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return ShoppingStorageLocation.class;
    }

    @Override
    public String getModelClassName() {
        return ShoppingStorageLocation.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("storageLocationId", getStorageLocationId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("name", getName());
        attributes.put("description", getDescription());
        attributes.put("location", getLocation());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long storageLocationId = (Long) attributes.get("storageLocationId");

        if (storageLocationId != null) {
            setStorageLocationId(storageLocationId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        String description = (String) attributes.get("description");

        if (description != null) {
            setDescription(description);
        }

        String location = (String) attributes.get("location");

        if (location != null) {
            setLocation(location);
        }
    }

    @JSON
    @Override
    public long getStorageLocationId() {
        return _storageLocationId;
    }

    @Override
    public void setStorageLocationId(long storageLocationId) {
        _storageLocationId = storageLocationId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    @JSON
    @Override
    public String getDescription() {
        if (_description == null) {
            return StringPool.BLANK;
        } else {
            return _description;
        }
    }

    @Override
    public void setDescription(String description) {
        _description = description;
    }

    @JSON
    @Override
    public String getLocation() {
        if (_location == null) {
            return StringPool.BLANK;
        } else {
            return _location;
        }
    }

    @Override
    public void setLocation(String location) {
        _location = location;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            ShoppingStorageLocation.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public ShoppingStorageLocation toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (ShoppingStorageLocation) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        ShoppingStorageLocationImpl shoppingStorageLocationImpl = new ShoppingStorageLocationImpl();

        shoppingStorageLocationImpl.setStorageLocationId(getStorageLocationId());
        shoppingStorageLocationImpl.setGroupId(getGroupId());
        shoppingStorageLocationImpl.setCompanyId(getCompanyId());
        shoppingStorageLocationImpl.setUserId(getUserId());
        shoppingStorageLocationImpl.setUserName(getUserName());
        shoppingStorageLocationImpl.setCreateDate(getCreateDate());
        shoppingStorageLocationImpl.setModifiedDate(getModifiedDate());
        shoppingStorageLocationImpl.setName(getName());
        shoppingStorageLocationImpl.setDescription(getDescription());
        shoppingStorageLocationImpl.setLocation(getLocation());

        shoppingStorageLocationImpl.resetOriginalValues();

        return shoppingStorageLocationImpl;
    }

    @Override
    public int compareTo(ShoppingStorageLocation shoppingStorageLocation) {
        long primaryKey = shoppingStorageLocation.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof ShoppingStorageLocation)) {
            return false;
        }

        ShoppingStorageLocation shoppingStorageLocation = (ShoppingStorageLocation) obj;

        long primaryKey = shoppingStorageLocation.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        ShoppingStorageLocationModelImpl shoppingStorageLocationModelImpl = this;

        shoppingStorageLocationModelImpl._originalGroupId = shoppingStorageLocationModelImpl._groupId;

        shoppingStorageLocationModelImpl._setOriginalGroupId = false;

        shoppingStorageLocationModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<ShoppingStorageLocation> toCacheModel() {
        ShoppingStorageLocationCacheModel shoppingStorageLocationCacheModel = new ShoppingStorageLocationCacheModel();

        shoppingStorageLocationCacheModel.storageLocationId = getStorageLocationId();

        shoppingStorageLocationCacheModel.groupId = getGroupId();

        shoppingStorageLocationCacheModel.companyId = getCompanyId();

        shoppingStorageLocationCacheModel.userId = getUserId();

        shoppingStorageLocationCacheModel.userName = getUserName();

        String userName = shoppingStorageLocationCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            shoppingStorageLocationCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            shoppingStorageLocationCacheModel.createDate = createDate.getTime();
        } else {
            shoppingStorageLocationCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            shoppingStorageLocationCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            shoppingStorageLocationCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        shoppingStorageLocationCacheModel.name = getName();

        String name = shoppingStorageLocationCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            shoppingStorageLocationCacheModel.name = null;
        }

        shoppingStorageLocationCacheModel.description = getDescription();

        String description = shoppingStorageLocationCacheModel.description;

        if ((description != null) && (description.length() == 0)) {
            shoppingStorageLocationCacheModel.description = null;
        }

        shoppingStorageLocationCacheModel.location = getLocation();

        String location = shoppingStorageLocationCacheModel.location;

        if ((location != null) && (location.length() == 0)) {
            shoppingStorageLocationCacheModel.location = null;
        }

        return shoppingStorageLocationCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(21);

        sb.append("{storageLocationId=");
        sb.append(getStorageLocationId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", description=");
        sb.append(getDescription());
        sb.append(", location=");
        sb.append(getLocation());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(34);

        sb.append("<model><model-name>");
        sb.append("com.fsquare.shopping.model.ShoppingStorageLocation");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>storageLocationId</column-name><column-value><![CDATA[");
        sb.append(getStorageLocationId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>description</column-name><column-value><![CDATA[");
        sb.append(getDescription());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>location</column-name><column-value><![CDATA[");
        sb.append(getLocation());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
