package com.fsquare.shopping.model.impl;

import com.fsquare.shopping.model.ShoppingItemImage;
import com.fsquare.shopping.service.ShoppingItemImageLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ShoppingItemImage service. Represents a row in the &quot;FsquareShopping_ShoppingItemImage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ShoppingItemImageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ShoppingItemImageImpl
 * @see com.fsquare.shopping.model.ShoppingItemImage
 * @generated
 */
public abstract class ShoppingItemImageBaseImpl
    extends ShoppingItemImageModelImpl implements ShoppingItemImage {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a shopping item image model instance should use the {@link ShoppingItemImage} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ShoppingItemImageLocalServiceUtil.addShoppingItemImage(this);
        } else {
            ShoppingItemImageLocalServiceUtil.updateShoppingItemImage(this);
        }
    }
}
