package com.fsquare.shopping.model.impl;

import com.fsquare.shopping.model.ShoppingStore;
import com.fsquare.shopping.service.ShoppingStoreLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ShoppingStore service. Represents a row in the &quot;FsquareShopping_ShoppingStore&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ShoppingStoreImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ShoppingStoreImpl
 * @see com.fsquare.shopping.model.ShoppingStore
 * @generated
 */
public abstract class ShoppingStoreBaseImpl extends ShoppingStoreModelImpl
    implements ShoppingStore {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a shopping store model instance should use the {@link ShoppingStore} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ShoppingStoreLocalServiceUtil.addShoppingStore(this);
        } else {
            ShoppingStoreLocalServiceUtil.updateShoppingStore(this);
        }
    }
}
