package com.fsquare.shopping.model.impl;

import com.fsquare.shopping.model.ShoppingItemType;
import com.fsquare.shopping.service.ShoppingItemTypeLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ShoppingItemType service. Represents a row in the &quot;FsquareShopping_ShoppingItemType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ShoppingItemTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ShoppingItemTypeImpl
 * @see com.fsquare.shopping.model.ShoppingItemType
 * @generated
 */
public abstract class ShoppingItemTypeBaseImpl extends ShoppingItemTypeModelImpl
    implements ShoppingItemType {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a shopping item type model instance should use the {@link ShoppingItemType} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ShoppingItemTypeLocalServiceUtil.addShoppingItemType(this);
        } else {
            ShoppingItemTypeLocalServiceUtil.updateShoppingItemType(this);
        }
    }
}
