package com.fsquare.shopping.model.impl;

import com.fsquare.shopping.model.ShoppingItemStorageLocation;
import com.fsquare.shopping.model.ShoppingItemStorageLocationModel;
import com.fsquare.shopping.model.ShoppingItemStorageLocationSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ShoppingItemStorageLocation service. Represents a row in the &quot;FsquareShopping_ShoppingItemStorageLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fsquare.shopping.model.ShoppingItemStorageLocationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ShoppingItemStorageLocationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ShoppingItemStorageLocationImpl
 * @see com.fsquare.shopping.model.ShoppingItemStorageLocation
 * @see com.fsquare.shopping.model.ShoppingItemStorageLocationModel
 * @generated
 */
@JSON(strict = true)
public class ShoppingItemStorageLocationModelImpl extends BaseModelImpl<ShoppingItemStorageLocation>
    implements ShoppingItemStorageLocationModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a shopping item storage location model instance should use the {@link com.fsquare.shopping.model.ShoppingItemStorageLocation} interface instead.
     */
    public static final String TABLE_NAME = "FsquareShopping_ShoppingItemStorageLocation";
    public static final Object[][] TABLE_COLUMNS = {
            { "itemStorageLocationId", Types.BIGINT },
            { "itemId", Types.BIGINT },
            { "storageLocationId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "name", Types.VARCHAR },
            { "quantity", Types.INTEGER }
        };
    public static final String TABLE_SQL_CREATE = "create table FsquareShopping_ShoppingItemStorageLocation (itemStorageLocationId LONG not null primary key,itemId LONG,storageLocationId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,quantity INTEGER)";
    public static final String TABLE_SQL_DROP = "drop table FsquareShopping_ShoppingItemStorageLocation";
    public static final String ORDER_BY_JPQL = " ORDER BY shoppingItemStorageLocation.itemStorageLocationId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY FsquareShopping_ShoppingItemStorageLocation.itemStorageLocationId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.fsquare.shopping.model.ShoppingItemStorageLocation"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.fsquare.shopping.model.ShoppingItemStorageLocation"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.fsquare.shopping.model.ShoppingItemStorageLocation"),
            true);
    public static long GROUPID_COLUMN_BITMASK = 1L;
    public static long ITEMID_COLUMN_BITMASK = 2L;
    public static long STORAGELOCATIONID_COLUMN_BITMASK = 4L;
    public static long ITEMSTORAGELOCATIONID_COLUMN_BITMASK = 8L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.fsquare.shopping.model.ShoppingItemStorageLocation"));
    private static ClassLoader _classLoader = ShoppingItemStorageLocation.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            ShoppingItemStorageLocation.class
        };
    private long _itemStorageLocationId;
    private long _itemId;
    private long _originalItemId;
    private boolean _setOriginalItemId;
    private long _storageLocationId;
    private long _originalStorageLocationId;
    private boolean _setOriginalStorageLocationId;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _companyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private String _name;
    private int _quantity;
    private long _columnBitmask;
    private ShoppingItemStorageLocation _escapedModel;

    public ShoppingItemStorageLocationModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static ShoppingItemStorageLocation toModel(
        ShoppingItemStorageLocationSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        ShoppingItemStorageLocation model = new ShoppingItemStorageLocationImpl();

        model.setItemStorageLocationId(soapModel.getItemStorageLocationId());
        model.setItemId(soapModel.getItemId());
        model.setStorageLocationId(soapModel.getStorageLocationId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setName(soapModel.getName());
        model.setQuantity(soapModel.getQuantity());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<ShoppingItemStorageLocation> toModels(
        ShoppingItemStorageLocationSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<ShoppingItemStorageLocation> models = new ArrayList<ShoppingItemStorageLocation>(soapModels.length);

        for (ShoppingItemStorageLocationSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _itemStorageLocationId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setItemStorageLocationId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _itemStorageLocationId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return ShoppingItemStorageLocation.class;
    }

    @Override
    public String getModelClassName() {
        return ShoppingItemStorageLocation.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("itemStorageLocationId", getItemStorageLocationId());
        attributes.put("itemId", getItemId());
        attributes.put("storageLocationId", getStorageLocationId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("name", getName());
        attributes.put("quantity", getQuantity());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long itemStorageLocationId = (Long) attributes.get(
                "itemStorageLocationId");

        if (itemStorageLocationId != null) {
            setItemStorageLocationId(itemStorageLocationId);
        }

        Long itemId = (Long) attributes.get("itemId");

        if (itemId != null) {
            setItemId(itemId);
        }

        Long storageLocationId = (Long) attributes.get("storageLocationId");

        if (storageLocationId != null) {
            setStorageLocationId(storageLocationId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        Integer quantity = (Integer) attributes.get("quantity");

        if (quantity != null) {
            setQuantity(quantity);
        }
    }

    @JSON
    @Override
    public long getItemStorageLocationId() {
        return _itemStorageLocationId;
    }

    @Override
    public void setItemStorageLocationId(long itemStorageLocationId) {
        _itemStorageLocationId = itemStorageLocationId;
    }

    @JSON
    @Override
    public long getItemId() {
        return _itemId;
    }

    @Override
    public void setItemId(long itemId) {
        _columnBitmask |= ITEMID_COLUMN_BITMASK;

        if (!_setOriginalItemId) {
            _setOriginalItemId = true;

            _originalItemId = _itemId;
        }

        _itemId = itemId;
    }

    public long getOriginalItemId() {
        return _originalItemId;
    }

    @JSON
    @Override
    public long getStorageLocationId() {
        return _storageLocationId;
    }

    @Override
    public void setStorageLocationId(long storageLocationId) {
        _columnBitmask |= STORAGELOCATIONID_COLUMN_BITMASK;

        if (!_setOriginalStorageLocationId) {
            _setOriginalStorageLocationId = true;

            _originalStorageLocationId = _storageLocationId;
        }

        _storageLocationId = storageLocationId;
    }

    public long getOriginalStorageLocationId() {
        return _originalStorageLocationId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    @JSON
    @Override
    public int getQuantity() {
        return _quantity;
    }

    @Override
    public void setQuantity(int quantity) {
        _quantity = quantity;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            ShoppingItemStorageLocation.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public ShoppingItemStorageLocation toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (ShoppingItemStorageLocation) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        ShoppingItemStorageLocationImpl shoppingItemStorageLocationImpl = new ShoppingItemStorageLocationImpl();

        shoppingItemStorageLocationImpl.setItemStorageLocationId(getItemStorageLocationId());
        shoppingItemStorageLocationImpl.setItemId(getItemId());
        shoppingItemStorageLocationImpl.setStorageLocationId(getStorageLocationId());
        shoppingItemStorageLocationImpl.setGroupId(getGroupId());
        shoppingItemStorageLocationImpl.setCompanyId(getCompanyId());
        shoppingItemStorageLocationImpl.setUserId(getUserId());
        shoppingItemStorageLocationImpl.setUserName(getUserName());
        shoppingItemStorageLocationImpl.setCreateDate(getCreateDate());
        shoppingItemStorageLocationImpl.setModifiedDate(getModifiedDate());
        shoppingItemStorageLocationImpl.setName(getName());
        shoppingItemStorageLocationImpl.setQuantity(getQuantity());

        shoppingItemStorageLocationImpl.resetOriginalValues();

        return shoppingItemStorageLocationImpl;
    }

    @Override
    public int compareTo(
        ShoppingItemStorageLocation shoppingItemStorageLocation) {
        long primaryKey = shoppingItemStorageLocation.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof ShoppingItemStorageLocation)) {
            return false;
        }

        ShoppingItemStorageLocation shoppingItemStorageLocation = (ShoppingItemStorageLocation) obj;

        long primaryKey = shoppingItemStorageLocation.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        ShoppingItemStorageLocationModelImpl shoppingItemStorageLocationModelImpl =
            this;

        shoppingItemStorageLocationModelImpl._originalItemId = shoppingItemStorageLocationModelImpl._itemId;

        shoppingItemStorageLocationModelImpl._setOriginalItemId = false;

        shoppingItemStorageLocationModelImpl._originalStorageLocationId = shoppingItemStorageLocationModelImpl._storageLocationId;

        shoppingItemStorageLocationModelImpl._setOriginalStorageLocationId = false;

        shoppingItemStorageLocationModelImpl._originalGroupId = shoppingItemStorageLocationModelImpl._groupId;

        shoppingItemStorageLocationModelImpl._setOriginalGroupId = false;

        shoppingItemStorageLocationModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<ShoppingItemStorageLocation> toCacheModel() {
        ShoppingItemStorageLocationCacheModel shoppingItemStorageLocationCacheModel =
            new ShoppingItemStorageLocationCacheModel();

        shoppingItemStorageLocationCacheModel.itemStorageLocationId = getItemStorageLocationId();

        shoppingItemStorageLocationCacheModel.itemId = getItemId();

        shoppingItemStorageLocationCacheModel.storageLocationId = getStorageLocationId();

        shoppingItemStorageLocationCacheModel.groupId = getGroupId();

        shoppingItemStorageLocationCacheModel.companyId = getCompanyId();

        shoppingItemStorageLocationCacheModel.userId = getUserId();

        shoppingItemStorageLocationCacheModel.userName = getUserName();

        String userName = shoppingItemStorageLocationCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            shoppingItemStorageLocationCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            shoppingItemStorageLocationCacheModel.createDate = createDate.getTime();
        } else {
            shoppingItemStorageLocationCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            shoppingItemStorageLocationCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            shoppingItemStorageLocationCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        shoppingItemStorageLocationCacheModel.name = getName();

        String name = shoppingItemStorageLocationCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            shoppingItemStorageLocationCacheModel.name = null;
        }

        shoppingItemStorageLocationCacheModel.quantity = getQuantity();

        return shoppingItemStorageLocationCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(23);

        sb.append("{itemStorageLocationId=");
        sb.append(getItemStorageLocationId());
        sb.append(", itemId=");
        sb.append(getItemId());
        sb.append(", storageLocationId=");
        sb.append(getStorageLocationId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", quantity=");
        sb.append(getQuantity());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(37);

        sb.append("<model><model-name>");
        sb.append("com.fsquare.shopping.model.ShoppingItemStorageLocation");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>itemStorageLocationId</column-name><column-value><![CDATA[");
        sb.append(getItemStorageLocationId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>itemId</column-name><column-value><![CDATA[");
        sb.append(getItemId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>storageLocationId</column-name><column-value><![CDATA[");
        sb.append(getStorageLocationId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>quantity</column-name><column-value><![CDATA[");
        sb.append(getQuantity());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
