package com.fsquare.shopping.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ShoppingStorageLocation service. Represents a row in the &quot;FsquareShopping_ShoppingStorageLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fsquare.shopping.model.impl.ShoppingStorageLocationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fsquare.shopping.model.impl.ShoppingStorageLocationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ShoppingStorageLocation
 * @see com.fsquare.shopping.model.impl.ShoppingStorageLocationImpl
 * @see com.fsquare.shopping.model.impl.ShoppingStorageLocationModelImpl
 * @generated
 */
public interface ShoppingStorageLocationModel extends BaseModel<ShoppingStorageLocation>,
    GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a shopping storage location model instance should use the {@link ShoppingStorageLocation} interface instead.
     */

    /**
     * Returns the primary key of this shopping storage location.
     *
     * @return the primary key of this shopping storage location
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this shopping storage location.
     *
     * @param primaryKey the primary key of this shopping storage location
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the storage location ID of this shopping storage location.
     *
     * @return the storage location ID of this shopping storage location
     */
    public long getStorageLocationId();

    /**
     * Sets the storage location ID of this shopping storage location.
     *
     * @param storageLocationId the storage location ID of this shopping storage location
     */
    public void setStorageLocationId(long storageLocationId);

    /**
     * Returns the group ID of this shopping storage location.
     *
     * @return the group ID of this shopping storage location
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this shopping storage location.
     *
     * @param groupId the group ID of this shopping storage location
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this shopping storage location.
     *
     * @return the company ID of this shopping storage location
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this shopping storage location.
     *
     * @param companyId the company ID of this shopping storage location
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this shopping storage location.
     *
     * @return the user ID of this shopping storage location
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this shopping storage location.
     *
     * @param userId the user ID of this shopping storage location
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this shopping storage location.
     *
     * @return the user uuid of this shopping storage location
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this shopping storage location.
     *
     * @param userUuid the user uuid of this shopping storage location
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this shopping storage location.
     *
     * @return the user name of this shopping storage location
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this shopping storage location.
     *
     * @param userName the user name of this shopping storage location
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this shopping storage location.
     *
     * @return the create date of this shopping storage location
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this shopping storage location.
     *
     * @param createDate the create date of this shopping storage location
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this shopping storage location.
     *
     * @return the modified date of this shopping storage location
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this shopping storage location.
     *
     * @param modifiedDate the modified date of this shopping storage location
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this shopping storage location.
     *
     * @return the name of this shopping storage location
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this shopping storage location.
     *
     * @param name the name of this shopping storage location
     */
    public void setName(String name);

    /**
     * Returns the description of this shopping storage location.
     *
     * @return the description of this shopping storage location
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this shopping storage location.
     *
     * @param description the description of this shopping storage location
     */
    public void setDescription(String description);

    /**
     * Returns the location of this shopping storage location.
     *
     * @return the location of this shopping storage location
     */
    @AutoEscape
    public String getLocation();

    /**
     * Sets the location of this shopping storage location.
     *
     * @param location the location of this shopping storage location
     */
    public void setLocation(String location);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.fsquare.shopping.model.ShoppingStorageLocation shoppingStorageLocation);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.fsquare.shopping.model.ShoppingStorageLocation> toCacheModel();

    @Override
    public com.fsquare.shopping.model.ShoppingStorageLocation toEscapedModel();

    @Override
    public com.fsquare.shopping.model.ShoppingStorageLocation toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
